[package]
name = "btree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.134"
num_enum = "0.5.7"

[lib]
crate-type = ["staticlib","lib"]

[profile.dev]
opt-level = 1